// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "run.h"

Fl_Double_Window* ScoobyDoo::make_window() {
  { Windows1 = new Fl_Double_Window(616, 424);
    Windows1->user_data((void*)(this));
    { LocationGroup = new Fl_Group(5, 5, 429, 90);
      LocationGroup->box(FL_ENGRAVED_BOX);
      { OldLocationInput = new Fl_Input(105, 20, 255, 20, "Old Location:");
      } // Fl_Input* OldLocationInput
      { NewLocationInput = new Fl_Input(105, 50, 255, 20, "New Location:");
      } // Fl_Input* NewLocationInput
      { SearchOldLocation = new Fl_Button(370, 20, 50, 20, "...");
      } // Fl_Button* SearchOldLocation
      { SearchNewLocation = new Fl_Button(370, 50, 50, 20, "...");
      } // Fl_Button* SearchNewLocation
      LocationGroup->end();
    } // Fl_Group* LocationGroup
    { ChoiceGroup = new Fl_Group(435, 5, 175, 90);
      ChoiceGroup->box(FL_ENGRAVED_BOX);
      { sn1Check = new Fl_Check_Button(450, 15, 80, 20, "new SN1");
        sn1Check->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* sn1Check
      { sn2Check = new Fl_Check_Button(450, 40, 80, 20, "new SN2");
        sn2Check->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* sn2Check
      { sd2Check = new Fl_Check_Button(450, 65, 80, 20, "new SD2");
        sd2Check->down_box(FL_DOWN_BOX);
      } // Fl_Check_Button* sd2Check
      ChoiceGroup->end();
    } // Fl_Group* ChoiceGroup
    { StatusGroup = new Fl_Group(5, 100, 605, 250);
      StatusGroup->box(FL_ENGRAVED_FRAME);
      { new Fl_Progress(15, 115, 585, 20, "label");
      } // Fl_Progress* o
      { new Fl_Text_Display(15, 140, 585, 200);
      } // Fl_Text_Display* o
      StatusGroup->end();
    } // Fl_Group* StatusGroup
    { SubmittionGroup = new Fl_Group(5, 355, 605, 55);
      SubmittionGroup->box(FL_ENGRAVED_BOX);
      { new Fl_Button(220, 370, 150, 25, "button");
      } // Fl_Button* o
      { Fl_Menu_Button* o = new Fl_Menu_Button(525, 375, 69, 20, "menu");
      } // Fl_Menu_Button* o
      SubmittionGroup->end();
    } // Fl_Group* SubmittionGroup
    Windows1->end();
  } // Fl_Double_Window* Windows1
  return Windows1;
}
